# Use postgres/example user/password credentials
version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbitmq
#    network_mode: host
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
    depends_on:
      - db

  web:
    build: ./web_service
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    env_file:
      - .env

  worker:
    build: ./worker
    restart: on-failure
    ports:
      - 8001:8000
    depends_on:
      - rabbitmq
    env_file:
      - .env